---

- name: get RCMCardDav release
  get_url:
    url: "https://github.com/mstilkerich/rcmcarddav/releases/download/v{{ roundcube_carddav_version }}/carddav-v{{ roundcube_carddav_version }}.tar.gz"
    dest: "{{ roundcube_path }}/plugins"
  register: carddav
  when: not ansible_check_mode

- name: unarchive RCMCardDav
  unarchive:
    src: "{{ roundcube_path }}/plugins/carddav-v{{ roundcube_carddav_version }}.tar.gz"
    dest: "{{ roundcube_path }}/plugins/"
    copy: no
  when: carddav.changed

- name: ensure current RCMCardDav config
  template:
    src: "plugins/carddav/config.inc.php.j2"
    dest: "{{ roundcube_path }}/plugins/carddav/config.inc.php"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0640
