---
- name: check if RCMCardDav release exists
  tags: roundcube
  stat:
    path: "{{ roundcube_working_dir }}/current/plugins/carddav-v{{ roundcube_carddav_version }}.tar.gz"
  register: roundcubemail_p_carddav_archive_file_exists

- name: Get RCMCardDav release
  tags: roundcube,roundcube-plugins,roundcube-carddav
  ansible.builtin.get_url:
    url: "https://github.com/mstilkerich/rcmcarddav/releases/download/v{{ roundcube_carddav_version }}/carddav-v{{ roundcube_carddav_version }}.tar.gz"
    dest: "{{ roundcube_working_dir }}/current/plugins"
    mode: "0644"
  register: carddav
  when: not ansible_check_mode and roundcubemail_p_carddav_archive_file_exists.stat.exists is false

- name: Unarchive RCMCardDav
  tags: roundcube,roundcube-plugins,roundcube-carddav
  ansible.builtin.unarchive:
    src: "{{ roundcube_working_dir }}/current/plugins/carddav-v{{ roundcube_carddav_version }}.tar.gz"
    dest: "{{ roundcube_working_dir }}/current/plugins/"
    copy: no
  when: carddav.changed

- name: Ensure current RCMCardDav config
  tags: roundcube,roundcube-plugins,roundcube-carddav
  ansible.builtin.template:
    src: "plugins/carddav/config.inc.php.j2"
    dest: "{{ roundcube_working_dir }}/current/plugins/carddav/config.inc.php"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0640"
