---
- name: Ensure enigma home is present
  tags: roundcube,roundcube-plugins,roundcube-enigma
  ansible.builtin.file:
    path: "{{ roundcube_enigma_home }}"
    state: directory
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0700"
