---

- name: Preflight checks
  tags: roundcube,roundcube-preflight
  ansible.builtin.import_tasks: preflight.yml

- name: Ensure roundcube group is present
  tags: roundcube
  ansible.builtin.group:
    name: "{{ roundcube_group }}"

- name: Ensure roundcube user is present
  tags: roundcube
  ansible.builtin.user:
    name: "roundcube"
    home: "{{ roundcube_user_home }}"
    shell: "{{ roundcube_user_shell }}"
    group: "{{ roundcube_group }}"

- name: Install Roundcube dependencies
  tags: roundcube
  ansible.builtin.apt:
    pkg: "{{ roundcube_dependencies }}"
    state: present
    install_recommends: False

- name: Check if roundcube directory exists
  tags: roundcube
  ansible.builtin.stat:
    path: "{{ roundcube_working_dir }}/roundcubemail-{{ roundcube_version }}"
  register: "roundcube_directory"

- name: check if roundcube release exists
  tags: roundcube
  stat:
    path: "{{ roundcube_working_dir }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
  register: roundcubemail_release_archive_file_exists

- name: Get roundcube release
  tags: roundcube
  ansible.builtin.get_url:
    url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
    dest: "{{ roundcube_working_dir }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0440"
  when: not ansible_check_mode and roundcubemail_release_archive_file_exists.stat.exists is false
  register: download

- name: Unarchive roundcube
  tags: roundcube
  ansible.builtin.unarchive:
    src: "{{ roundcube_working_dir }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
    dest: "{{ roundcube_working_dir }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0750"
    copy: no
  when: (download.changed) or
    (not roundcube_directory.stat.exists) or
    (roundcube_enable_installer | bool)

- name: Link to current roundcube release
  tags: roundcube
  ansible.builtin.file:
    src: "{{ roundcube_working_dir }}/roundcubemail-{{ roundcube_version }}"
    dest: "{{ roundcube_working_dir }}/current"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    state: link
    follow: False
    mode: "0777"
  register: link
  notify: Restart webserver

- name: Link www to current roundcube release public_html directory
  tags: roundcube
  ansible.builtin.file:
    src: "{{ roundcube_working_dir }}/current/public_html"
    dest: "{{ roundcube_path }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    state: link
    follow: False
    mode: "0777"
  register: link
  notify: Restart webserver

- name: Make sure that the following directories (and the files within) are writable by the webserver
  tags: roundcube
  ansible.builtin.file:
    path: "{{ roundcube_working_dir }}/current/{{ item }}"
    state: directory
    owner: "www-data"
    group: "{{ roundcube_group }}"
    recurse: true
    mode: "u+rwX,go+rX,go-w"
  with_items:
    - 'temp'
    - 'logs'

- name: Ensure roundcube and plugin configs are latest
  tags: roundcube,roundcube-sieve,skin-skin
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ roundcube_working_dir }}/current/{{ item }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0640"
  with_items:
    - config/config.inc.php
    - "{{ roundcube_configs_extra | default() }}"

- name: Run roundcube upgrade script
  tags: roundcube
  ansible.builtin.command: "{{ roundcube_working_dir }}/current/bin/update.sh"
  changed_when: true
  when:
    - link.changed
    - ( not roundcube_enable_installer | bool )
    - not testing|default(False)

# cron replaced by systemd timer and service
- name: copy systemd files
  tags: roundcube
  ansible.builtin.template:
    src: "systemd_system//{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "roundcube-cleaning-jobs.service.j2"
    - "roundcube-cleaning-jobs.timer.j2"

- name: enable and start roundcube-cleaning-jobs timer unit
  tags: roundcube,roundcube-systemd
  ansible.builtin.systemd:
    name: roundcube-cleaning-jobs.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Import skining tasks
  tags: roundcube,roundcube-skin
  ansible.builtin.import_tasks: skin.yml

- name: Import carddav plugin tasks
  tags: roundcube,roundcube-plugins,roundcube-carddav
  ansible.builtin.import_tasks: carddav.yml
  when: "'carddav' in roundcube_plugins"

- name: Import enigma plugin tasks
  tags: roundcube,roundcube-plugins,roundcube-enigma
  ansible.builtin.import_tasks: enigma.yml
  when: "'enigma' in roundcube_plugins"

- name: Import extra plugin tasks
  tags: roundcube,roundcube-plugins,roundcube-extra-plugins
  ansible.builtin.include_tasks: extra-plugins.yml
  when: "roundcube_plugins_extra is defined"
  loop: "{{ roundcube_plugins_extra }}"

- name: Ensure the installer directory is deleted
  tags: roundcube
  ansible.builtin.file:
    path: "{{ roundcube_working_dir }}/current/installer"
    state: absent
  when: ( not roundcube_enable_installer | bool )
