---
- name: ensure roundcube user is present
  user:
    name: "{{ roundcube_user }}"
    home: "{{ roundcube_user_home }}"
    shell: "{{ roundcube_user_shell }}"

- name: ensure database user is present
  mysql_user:
    name: "{{ roundcube_mysql_user }}"
    password: "{{ roundcube_mysql_password }}"
    priv: "{{ roundcube_mysql_db }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ roundcube_root_mysql_password }}"

- name: ensure database is present
  mysql_db:
    name: "{{ roundcube_mysql_db }}"
    state: present
    encoding: "utf8"
    collation: "utf8_general_ci"
    login_user: root
    login_password: "{{ roundcube_root_mysql_password }}"
  notify: Import database

- name: install Roundcube dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: False
  with_items: "{{ roundcube_dependencies }}"

- name: register version
  shell: "grep -m1 {{ roundcube_version }} {{ roundcube_path }}/CHANGELOG | sed 's/RELEASE //'"
  register: version
  check_mode: no
  changed_when: False
  ignore_errors: yes

- name: get roundcube release
  get_url:
    url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
    dest: "{{ roundcube_user_home }}"
  when: version.stdout != roundcube_version

- name: unarchive roundcube
  unarchive:
    src: "{{ roundcube_user_home }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
    dest: "{{ roundcube_user_home }}"
    copy: no
  when: version.stdout != roundcube_version

- name: sync current roundcube directory
  synchronize:
    src: "{{ roundcube_user_home }}/roundcubemail-{{ roundcube_version }}/"
    dest: "{{ roundcube_path }}"
  delegate_to: "{{ inventory_hostname }}"
  when: version.stdout != roundcube_version

- name: change owner+group to roundcube user
  file:
    path: "{{ roundcube_path }}"
    state: directory
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    recurse: yes
  when: version.stdout != roundcube_version

- import_tasks: carddav.yml
  tags:
    - carddav

- name: ensure roundcube and plugin configs are latest
  template:
    src: "{{ item }}.j2"
    dest: "{{ roundcube_path }}/{{ item }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0640
  with_items:
    - config/config.inc.php
    - "{{ roundcube_configs_extra|d() }}"
  tags:
    - sieve
    - carddav

- name: run roundcube upgrade script
  command: "{{ roundcube_path }}/bin/update.sh -v {{ version.stdout }}"
  when: (version.stdout != roundcube_version) and (version.stdout != '')

- name: copy custom favicon
  copy:
    src: "{{ roundcube_custom_favicon_path }}"
    dest: "{{ roundcube_path }}/skins/{{ item }}/images/favicon.ico"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0644
  with_items:
    - classic
    - larry
  when: roundcube_custom_favicon_path|d()

- name: create Roundcube cleandb cronjob
  cron:
    name: "Roundcube cleandb cronjob"
    minute: 10
    hour: 6
    user: "{{ roundcube_user }}"
    job: "{{ roundcube_path }}/bin/cleandb.sh >/dev/null"
    cron_file: roundcube

- name: create Roundcube garbage collector cronjob
  cron:
    name: "Roundcube garbage collector cronjob"
    minute: 30
    user: "{{ roundcube_user }}"
    job: "{{ roundcube_path }}/bin/gc.sh >/dev/null"
    cron_file: roundcube

- name: Create custom image directory
  file:
    path: "{{ roundcube_path }}/images"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0755
    state: directory

- name: Copy custom logo to image directory
  copy:
    src: "{{ roundcube_custom_logo }}"
    dest: "{{ roundcube_path }}/images/{{ roundcube_custom_logo }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0644
  when: roundcube_custom_logo is defined

- name: set custom link for click on logo
  replace:
    path: "{{ roundcube_path }}/skins/{{ item }}/includes/header.html"
    regexp: '(.*)name="logo"(.*)onclick="(.*?)"(.*)'
    replace: "\\1name=\"logo\"\\2onclick=\"location.href='{{ roundcube_logo_url }}'\"\\4"
  with_items:
    - classic
    - larry
  when: roundcube_logo_url is defined

- name: ensure installed release archive is absent
  file:
    path: "{{ roundcube_user_home }}/roundcubemail-{{ roundcube_version }}{{ item }}"
    state: absent
  with_items:
    - '-complete.tar.gz'
    - ''

- import_tasks: getmail.yml
  tags:
    - getmail
