---

- name: create custom skin dir for elastic skin
  synchronize:
    src: elastic_systemli
    dest:  "{{ roundcube_path }}/skins/"
    owner: false
    group: false
  when: roundcube_skin == 'elastic_systemli'

- name: ensure custom skin dir has correct permissions
  file:
    path:  "{{ roundcube_path }}/skins/{{ roundcube_skin }}/"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    recurse: true
  when: roundcube_skin == 'elastic_systemli'

- name: copy custom logo to image directory
  copy:
    src: "{{ roundcube_custom_logo }}"
    dest: "{{ roundcube_path }}/skins/{{ roundcube_skin }}/images/{{ roundcube_custom_logo }}"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0644
  when: roundcube_custom_logo is defined

- name: copy custom favicon
  copy:
    src: "{{ roundcube_custom_favicon_path }}"
    dest: "{{ roundcube_path }}/skins/{{ roundcube_skin }}/images/favicon.ico"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0644
  when: roundcube_custom_favicon_path|d()
