---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-roundcube"
      ansible.builtin.include_role:
        name: "ansible-role-roundcube"
      vars:
        roundcube_mysql_password: "password"
        roundcube_des_key: "SuperS3cr3tD3SKeys"
        testing: true
